export default {
  LOGIN_REQUEST_FETCHING: 'LOGIN_REQUEST_FETCHING',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',

  REGISTER_REQUEST_FETCHING: 'REGISTER_REQUEST_FETCHING',
  REGISTER_REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS',
  REGISTER_REQUEST_FAIL: 'REGISTER_REQUEST_FAIL',

  LOGOUT: 'LOGOUT',

  SET_LOGIN_STATE: 'SET_LOGIN_STATE'
}
