export default {

  /*
  * Request Boards
  */
   GET_BOARDS_FETCHING : 'GET_BOARDS_FETCHING',
   GET_BOARDS_SUCCESS : 'GET_BOARDS_SUCCESS',
   GET_BOARDS_FAILURE : 'GET_BOARDS_FAILURE',

   /*
   * Create new Board
   */
   CREATE_BOARD_FETCHING: 'CREATE_BOARD_FETCHING',
   CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
   CREATE_BOARD_FAILURE: 'CREATE_BOARD_FAILURE',

   /*
   * Delete Board
   */
   DELETE_BOARD_FETCHING: 'DELETE_BOARD_FETCHING',
   DELETE_BOARD_SUCCESS: 'DELETE_BOARD_SUCCESS',
   DELETE_BOARD_FAILURE: 'DELETE_BOARD_FAILURE',

   /*
   * Update Board
   */
   UPDATE_BOARD_FETCHING: 'UPDATE_BOARD_FETCHING',
   UPDATE_BOARD_SUCCESS: 'UPDATE_BOARD_SUCCESS',
   UPDATE_BOARD_FAILURE: 'UPDATE_BOARD_FAILURE',


}
