export default {

  /*
  * Get All Lists
  */
  GET_LISTS_FETCHING: 'GET_LISTS_FETCHING',
  GET_LISTS_SUCCESS: 'GET_LISTS_SUCCESS',
  GET_LISTS_FAILURE: 'GET_LISTS_FAILURE',

  /*
  * Update List
  */
  UPDATE_LIST_FETCHING: 'UPDATE_LIST_FETCHING',
  UPDATE_LIST_SUCCESS: 'UPDATE_LIST_SUCCESS',
  UPDATE_LIST_FAILURE: 'UPDATE_LIST_FAILURE',

  /*
  * Create List
  */
  CREATE_LIST_FETCHING: 'CREATE_LIST_FETCHING',
  CREATE_LIST_SUCCESS: 'CREATE_LIST_SUCCESS',
  CREATE_LIST_FAILURE: 'CREATE_LIST_FAILURE',

  /*
  * Delete List
  */
  DELETE_LIST_FETCHING: 'DELETE_LIST_FETCHING',
  DELETE_LIST_SUCCESS: 'DELETE_LIST_SUCCESS',
  DELETE_LIST_FAILURE: 'DELETE_LIST_FAILURE',

  /*
  * Get All Cards
  */
  GET_CARDS_FETCHING: 'GET_CARDS_FETCHING',
  GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
  GET_CARDS_FAILURE: 'GET_CARDS_FAILURE',

  /*
  * Create Card
  */
  CREATE_CARD_FETCHING: 'CREATE_CARD_FETCHING',
  CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',
  CREATE_CARD_FAILURE: 'CREATE_CARD_FAILURE',

  /*
  * Update Card
  */
  UPDATE_CARD_FETCHING: 'UPDATE_CARD_FETCHING',
  UPDATE_CARD_SUCCESS: 'UPDATE_CARD_SUCCESS',
  UPDATE_CARD_FAILURE: 'UPDATE_CARD_FAILURE',

  /*
  * Delete Card
  */
  DELETE_CARD_FETCHING: 'DELETE_CARD_FETCHING',
  DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
  DELETE_CARD_FAILURE: 'DELETE_CARD_FAILURE',

}
